import sqlite3

conn =sqlite3.connect("DBGallery.db")

conn.execute('''CREATE TABLE IF NOT EXISTS EXHIBITION
    ( ID INTEGER NOT NULL,
    Title TEXT NOT NULL,
    Cost FLOAT NOT NULL,
    Date_Import DATE NOT NULL,
    Date_Export DATE,
    Periodical BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (ID),
    CONSTRAINT PERIODIC_TRUE CHECK (Periodical == FALSE OR Date_Export IS NOT NULL));''')

conn.execute('''CREATE TABLE IF NOT EXISTS HALL
    ( ID INTEGER NOT NULL,
    Area FLOAT NOT NULL,
    Floor INTEGER DEFAULT 0,
    Wing VARCHAR(255),
    Capacity INTEGER NOT NULL,
    ID_Exhibition INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY(ID_Exhibition) REFERENCES EXHIBITION(ID) ON DELETE SET NULL ON UPDATE CASCADE);''')

conn.execute('''CREATE TABLE IF NOT EXISTS ARTIST
    ( ID INTEGER NOT NULL,
    Biography TEXT,
    Gender VARCHAR(15),
    Year_of_death INTEGER,
    Year_of_birth INTEGER,
    Place_of_birth VARCHAR(20),
    First_Name VARCHAR(20) DEFAULT "Anonymous",
    Middle_Name VARCHAR(20),
    Last_Name VARCHAR(20),
    Nickname VARCHAR(20),
    PRIMARY KEY (ID));''')

conn.execute('''CREATE TABLE IF NOT EXISTS ARTWORK
    ( ID INTEGER NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Material VARCHAR(255),
    Dimensions VARCHAR(30),
    Type VARCHAR(30) NOT NULL,
    Year_of_creation INTEGER,
    Description TEXT,
    Current_of_influence VARCHAR(255),
    ID_Exhibition INTEGER,
    ID_Hall INTEGER,
    ID_Artist INTEGER,
    PRIMARY KEY (ID),
    FOREIGN KEY(ID_Exhibition) REFERENCES EXHIBITION(ID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY(ID_Hall) REFERENCES HALL(ID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY(ID_Artist) REFERENCES ARTIST(ID) ON DELETE RESTRICT ON UPDATE CASCADE);''')

conn.execute('''CREATE TABLE IF NOT EXISTS TICKET
    ( ID INTEGER NOT NULL,
    Date_issuing DATETIME NOT NULL,
    Date_expiring DATETIME NOT NULL,
    Price FLOAT NOT NULL,
    Buyer VARCHAR(255),
    Multiplicity INTEGER DEFAULT 1,
    Discount FLOAT DEFAULT 0,
    Time_of_arrival TIME NOT NULL,
    PRIMARY KEY (ID));''')

conn.execute('''CREATE TABLE IF NOT EXISTS TICKET_CONTAINS
    ( ID_Ticket INTEGER NOT NULL,
    ID_Exhibition INTEGER NOT NULL,
    PRIMARY KEY (ID_Ticket,ID_Exhibition),
    FOREIGN KEY(ID_Ticket) REFERENCES TICKET(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(ID_Exhibition) REFERENCES EXHIBITION(ID) ON DELETE CASCADE ON UPDATE CASCADE);''')

conn.execute('''CREATE TABLE IF NOT EXISTS EXTERNAL_INSTITUTION
    ( ID INTEGER NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Date_arrangement DATETIME NOT NULL,
    Date_borrowing DATE NOT NULL,
    Date_return DATE,
    Contract INTEGER NOT NULL,
    PRIMARY KEY (ID));''')

conn.execute('''CREATE TABLE IF NOT EXISTS BORROWS_FROM
    ( ID_Borrowing INTEGER NOT NULL,
    ID_Artwork INTEGER NOT NULL,
    PRIMARY KEY (ID_Artwork,ID_Borrowing),
    FOREIGN KEY(ID_Artwork) REFERENCES ARTWORK(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(ID_Borrowing) REFERENCES EXTERNAL_INSTITUTION(ID) ON DELETE CASCADE ON UPDATE CASCADE);''')

conn.execute('''CREATE TABLE IF NOT EXISTS BORROWS_TO
    ( ID_Borrowing INTEGER NOT NULL,
    ID_Artwork INTEGER NOT NULL,
    PRIMARY KEY (ID_Artwork,ID_Borrowing),
    FOREIGN KEY(ID_Artwork) REFERENCES ARTWORK(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(ID_Borrowing) REFERENCES EXTERNAL_INSTITUTION(ID) ON DELETE CASCADE ON UPDATE CASCADE);''') 

conn.execute('''CREATE TABLE IF NOT EXISTS EMPLOYEE
    ( VAT INTEGER NOT NULL,
    Email VARCHAR(255),
    Gender VARCHAR(15),
    Job_position VARCHAR(30) NOT NULL,
    Salary INTEGER NOT NULL,
    Name VARCHAR(20) NOT NULL,
    Middle_Name VARCHAR(20),
    Last_Name VARCHAR(20) NOT NULL,
    Contact_number INTEGER NOT NULL,
    VAT_Supervisor INTEGER,
    PRIMARY KEY (VAT),
    FOREIGN KEY(VAT_Supervisor) REFERENCES EMPLOYEE(VAT) ON DELETE SET NULL ON UPDATE CASCADE);''')

conn.execute('''CREATE TABLE IF NOT EXISTS EMPLOYEE_MAINTENANCE
    ( VAT INTEGER NOT NULL,
    Specialty VARCHAR(30) NOT NULL,
    PRIMARY KEY (VAT),
    FOREIGN KEY(VAT) REFERENCES EMPLOYEE(VAT) ON DELETE CASCADE ON UPDATE CASCADE);''')

conn.execute('''CREATE TABLE IF NOT EXISTS MAINTENANCE
    ( ID_Artwork INTEGER NOT NULL,
    Lab VARCHAR(10) NOT NULL,
    Date_import DATE NOT NULL,
    Expected_date_export DATE NOT NULL,
    Date_export DATE,
    VAT_Supervisor INTEGER NOT NULL,
    PRIMARY KEY (ID_Artwork,Date_import),
    FOREIGN KEY(ID_Artwork) REFERENCES ARTWORK(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(VAT_Supervisor) REFERENCES EMPLOYEE_MAINTENANCE(VAT) ON DELETE NO ACTION ON UPDATE CASCADE);''')

conn.execute('''CREATE TABLE IF NOT EXISTS CONDUCTS_MAINTENANCE
    ( ID_Artwork INTEGER NOT NULL,
    VAT INTEGER NOT NULL,
    Date_import DATE NOT NULL,
    PRIMARY KEY (ID_Artwork,VAT,Date_import),
    FOREIGN KEY(ID_Artwork,Date_import) REFERENCES MAINTENANCE(ID_Artwork,Date_import) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(VAT) REFERENCES EMPLOYEE_MAINTENANCE(VAT) ON DELETE CASCADE ON UPDATE CASCADE);''')

conn.close()
